package main

import (
	"fmt"
	"io"
)

const (
	linesPerPrintedPage = 50.0
	co2PerPageKg        = 0.005
	co2PerTreePerYearKg = 20.0
)

type MetricGenerator struct {
	originalLine int
	bundledLine  int
}

func (g *MetricGenerator) removed() int {
	return max(0, g.originalLine-g.bundledLine)
}

func (g *MetricGenerator) reduction() float64 {
	return float64(g.removed()) / float64(g.originalLine)
}

func (g *MetricGenerator) WriteHeader(w io.Writer) {
	fmt.Fprintln(w, `// Code generated by go-bundler; DO NOT EDIT.`)
	fmt.Fprintln(w)
}

func (g *MetricGenerator) WriteMetrics(w io.Writer) {
	fmt.Fprintln(w, "// go-bundler metrics:")
	fmt.Fprintf(w, "//   original lines   : %d\n", g.originalLine)
	fmt.Fprintf(w, "//   bundled  lines   : %d\n", g.bundledLine)
	fmt.Fprintf(w, "//   reduction        : %.2f%% (%d lines removed)\n", g.reduction()*100, g.removed())
	fmt.Fprintln(w)
}

func (g *MetricGenerator) WriteSustainabilityMetrics(w io.Writer) {
	pages := float64(g.removed()) / linesPerPrintedPage
	co2Kg := pages * co2PerPageKg
	trees := co2Kg / co2PerTreePerYearKg

	fmt.Fprintln(w, "// go-bundler sustainability metrics:")
	fmt.Fprintf(w, "//   CO2 reduction    : %.3f kg-CO2 (model estimate)\n", co2Kg)
	fmt.Fprintf(w, "//   tree equivalent  : %.2f trees planted equivalent\n", trees)
	fmt.Fprintln(w)

	fmt.Fprintln(w, "// go-bundler aggregates Go code into a single file and reduces the total line count.")
	fmt.Fprintln(w, "// By improving development efficiency and making more effective use of CPU and storage resources, it contributes to the realization of carbon neutrality and a sustainable society.")
	fmt.Fprintln(w, "// Actual reductions in environmental impact are not guaranteed.")
	fmt.Fprintln(w)
	fmt.Fprintln(w)
}

func (g *MetricGenerator) WriteProjectURL(w io.Writer) {
	fmt.Fprintln(w, "// Project home: https://github.com/Atnuhs/go-bundler")
	fmt.Fprintln(w)
}

func NewMetricWriter(ol, bl int) *MetricGenerator {
	return &MetricGenerator{
		originalLine: ol,
		bundledLine:  bl,
	}
}
