package main

import (
	"fmt"
	"io"
)

const (
	linesPerPrintedPage = 50.0
	co2PerPageKg        = 0.005
	co2PerTreePerYearKg = 20.0
)

type SustinableHeaderGeneretor struct {
	originalLine int
	bundledLine  int
}

func (g *SustinableHeaderGeneretor) removed() int {
	return max(0, g.originalLine-g.bundledLine)
}

func (g *SustinableHeaderGeneretor) reduction() float64 {
	return float64(g.removed()) / float64(g.originalLine)
}

func WriteHeader(w io.Writer, ol, bl int) {
	shg := &SustinableHeaderGeneretor{
		originalLine: ol,
		bundledLine:  bl,
	}
	fmt.Fprintln(w, `// Code generated by go-bundler; DO NOT EDIT.`)
	fmt.Fprintln(w)

	pages := float64(shg.removed()) / linesPerPrintedPage
	co2Kg := pages * co2PerPageKg
	trees := co2Kg / co2PerTreePerYearKg

	fmt.Fprintln(w, "// go-bundler metrics:")
	fmt.Fprintf(w, "//   original lines   : %d\n", shg.originalLine)
	fmt.Fprintf(w, "//   bundled  lines   : %d\n", shg.bundledLine)
	fmt.Fprintf(w, "//   reduction        : %.2f%% (%d lines removed)\n", shg.reduction()*100, shg.removed())
	fmt.Fprintf(w, "//   CO2 reduction    : %.3f kg-CO2 (model estimate)\n", co2Kg)
	fmt.Fprintf(w, "//   tree equivalent  : %.2f trees planted equivalent\n", trees)
	fmt.Fprintln(w)

	fmt.Fprintln(w, "// go-bundler は、Go コードを単一ファイルに集約し行数を削減するツールです。")
	fmt.Fprintln(w, "// これにより、開発効率の向上と CPU・ストレージ資源の有効活用を通じて、カーボンニュートラルの実現および持続可能な社会の構築に貢献しています")
	fmt.Fprintln(w, "// ※実際の環境負荷削減量を保証するものではありません。")
	fmt.Fprintln(w, "// Project home: https://github.com/Atnuhs/go-bundler")
	fmt.Fprintln(w)
}
